version: "3.9"

services:
  nginx: 
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build: ./.docker/php-fpm
    volumes:
      - ./.docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./src:/var/www/html
    links:
      - mariadb

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - "./data/db:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    links:
      - mariadb