version: "3.9"

services:
  nginx: 
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build: 
      context: ./.docker/php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./.docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./src:/var/www/html